### ISSUE TITLE
Create an OpenRefine endpoint & add to user documentation

### ISSUE THREAD

**Issue by dshorthouse** [gnames/gnames#101]
Latest specs: https://reconciliation-api.github.io/specs/latest/
User request: https://twitter.com/AWhitTwit/status/1570163562638876672

**Comment by dimus** [comment]
OpenRefine reconciliation works now when using `https://verifier.globalnames.org/api/v1/reconcile` as a reconciliation URL.

![image](https://github.com/gnames/gnames/assets/12124/40eaecf3-f2f3-46d7-a840-a95aaeca3c35)

However, I do not think I am out of the woods yet. @amandawhitmire can we make a screen-sharing call? It would be helpful to get your feedback about this functionality.

I do not have documentation yet, in case if something will have to be changed significantly. Also I would like to add some more useful features to the service.

**Comment by amandawhitmire** [comment]
@dimus this is fantastic! Very happy to have a screen-sharing call with you. When works? What time zone are you in? I'm GMT-7 (Pacific Daylight Time).

**Comment by dimus** [comment]
Great @amandawhitmire! I am CDT (GMT -5), I am free after lunch on Monday, all day Tuesday. You can write me at dmozzherin@gmail.com to choose a time that is good for you.

**Comment by dimus** [comment]
@amandawhitmire, thank you for starting documentation at https://github.com/gnames/gnverifier/wiki/OpenRefine-readme
