### ISSUE TITLE
As a User of reconciliation service I want to get "good" results matching automatically

### ISSUE THREAD

**Issue by dimus** [gnames/gnames#107]
Related to https://github.com/gnames/gnames/issues/101

For this we need to figure out criteria that make a candidate a 'match' and formalize them in the reconciliation score.

Sorting of the results will still be done by verification score, but if the first result gains good enough reconciliation score, it will be marked as 'matched'

**Comment by amandawhitmire** [comment]
Someone asked me about this today, so I gave the reconciliation another spin. None of my results were "matched" automatically - maybe there is a setting in the reconciliation that I missed. Is it still at https://verifier.globalnames.org/api/v1/reconcile ?

**Comment by dimus** [comment]
Hi @amandawhitmire, can you have another try? Automatic match should work now
