### ISSUE TITLE
replicate gnames services at a very small and local scale

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnames#72]
I came from this [gnverifier question](https://github.com/gnames/gnverifier/issues/62).

I wonder if, as a future gnames small data provider, I could also run a gnames web server providing name matching services but **limited only to those datasets of my interest** (i.e., my own data and perhaps also a small subset of certain plants and fungi extracted from currently available huge datasets, but filtering only the names of those taxa occurring in my region). 
Is this in theory possible? And specially, would this limited data size permit to reduce [hardware requeriments](https://github.com/gnames/gnames#installation-prerequesites)? 

In [gnames documentation](https://github.com/gnames/gnames#installation-process) I see it's possible to download a gnames pgsql database dump. So after doing it, I could filter out the vast majority of data to keep only my own selection of names. This could solve the other [question I posted in gnmatcher](https://github.com/gnames/gnmatcher/issues/39), I guess.
Of course, assuming I am able to understand the database structure in order to load my own data (those names I can't find in gnames yet -if there is any-). 
Is there a gnames ER schema available somewhere?

Do I need specific postgresql client/server versions to restore the dump? I created the gnames database and tried the suggested restore command (from psql client 10.19) on two different remote servers (9.2.15 and also 12.6), but I got the same error in both cases:
```
$ pg_restore --version
pg_restore (PostgreSQL) 10.19 (Ubuntu 10.19-0ubuntu0.18.04.1)

$ gunzip -c gnames_latest.sql.gz | pg_restore -h postgresql.server.ip -d gnames -U psql_user
pg_restore: [archiver] unsupported version (1.14) in file header
```
By the way, many of the [data sources](https://verifier.globalnames.org/data_sources) versions are quite recent: 1, 2, 3, 5, 9, 11, 12 ... (many more) ... 193, 194, 195: were updated during 2021.  But the linked database dump is quite old ([gnames-latest.sql.gz 28-Nov-2020](http://opendata.globalnames.org/dumps/gnames-latest.sql.gz)). How frequently is it updated?

Thanks a lot in advance for your answers (and your patience)

**Comment by dimus** [comment]
It is in plans, but not the highest in priority. I hope if we will get another round of funding it will happen faster than later. I am going to update the database dump somewhere in January 2022 after updating data sources this December.

**Comment by dimus** [comment]
I do need a bit of trickery to get gnames/gnmatcher running. I would like to get to v1 for both of them first, and then start the process of making it easier for people to run the service locally. Now gnames and gnmatcher still change in backward incompatible way, so I would say setting up the system at the moment requires some diving into database and code, and writing documentation for moving target would mean less progess is done for the projects themselves.

**Comment by abubelinha** [comment]
I understand. 
In the mean time I would be happy just knowing how to prepare a VM capable to import the avaliable dump and play with it (no more questions about ER ... LOL).

There must be some kind of incompatibility depnding on pg_restore version. It would help to know which one you use.

**Comment by dimus** [comment]
Database changed quite a bit, I will put new version in January, but still, as I mentioned it would require trial, error and despair until versions 1 for gnverifier
