### ISSUE TITLE
Missing column in table

### ISSUE THREAD

**Issue by abrami** [gnames/gnames#76]
Within the application, when called, a select is performed in Postgres that queries a column that does not exist: "is_outlink_ready" in public.data_sources. Therefore the application cannot be started. The database import was performed with the current export.

Furthermore, I am a bit surprised that I do not receive any feedback via the API for many entries. If all three installation steps (DB, gnmatcher and gnames) are installed, it should be just a self-runner?

Thanks for your help.

**Comment by dimus** [comment]
@abrami, are you trying to run it locally?

**Comment by dimus** [comment]
No further feedback, closing...
