### ISSUE TITLE
Exact match returns variations in suffixes (exact match by stem)

### ISSUE THREAD

**Issue by dimus** [gnames/gnames#82]
This issue is related to conversation at https://github.com/gnames/gnverifier/issues/80

**Comment by dimus** [comment]
@abubelinha, this one is life now
https://verifier.globalnames.org/api/v0/verifications/Isoetes%20longissimum?data_sources=0&all_matches=true

**Comment by abubelinha** [comment]
This looks much much better indeed.
It's beginning to return some first letter I/J orthovariants as well, that's great!

http://verifier.globalnames.org/api/v0/verifications/Jsoetes%20longissimum?data_sources=196|197|198|158&all_matches=true

**Comment by abubelinha** [comment]
Hold on @dimus ... it has broken again? 

Why does this similar example not return any names?
http://verifier.globalnames.org/api/v0/verifications/Teucrium%20pyrenaicum%20subsp.%20guarense?data_sources=196%7C197%7C198%7C158&all_matches=true

Perhaps you only corrected it to matching fuzzy species names, but not infraspecies?

**Comment by dimus** [comment]
Definitely a bug will fix it hopefully today. https://github.com/gnames/gnames/issues/90

**Comment by dimus** [comment]
Fixed and published with a lot of other changes. @abubelinha please read https://github.com/gnames/gnames/releases/tag/v0.8.0
