### ISSUE TITLE
what is names[x].matchType?

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnames#83]
Not sure if this has to be reported in gnverifier or gnames project, but I let it here since I came from #82

As I understand from [api v0 doc](https://apidoc.globalnames.org/gnames-beta), json results:
- `names[x].bestResult.matchType` "describes the matching type between the input name-string and the matched name from the data-source"
- `names[x].matchType` "indicates the quality of verification", where "NoMatch" means "no matched name found". Although this parameter is flagged with a red asterisk (*)

Sorry, but I don't get what is the difference between them. Perhaps the red asterisk flag means "deprecated"?
(worth to mention, matchType categories are described in the flagged one, but not in the other)

http://verifier.globalnames.org/api/v0/verifications/Jsoetes%20cf.%20longissimum%20Bory?data_sources=196|197|198|158&all_matches=true

In the above example, why is `names[x].matchType="NoMatch"` while the other is `names[x].bestResult.matchType="Fuzzy"`?

**Comment by dimus** [comment]
names[x].matchType and names[x].bestResult.matchType should be exactly the same. names[x].matchType is a convenience field

asterisk means that this field is required. I'll add this explanation to documentation

**Comment by dimus** [comment]
Added #84, #87, https://github.com/gnames/gnapi/issues/4

**Comment by dimus** [comment]
I think issues from this converation are fixed, closing
