### ISSUE TITLE
add dataSourcesList next to dataSourcesNum

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnames#92]
With new API changes, if we don't provide no list of preferred datasources, we get only a bestResult.
There is no way to get ALL matches unless you explicit ALL datasources in a preferred list.

```json
// 20220313103348
// https://verifier.globalnames.org/api/v0/verifications/Narcissus%20minor

{
  "metadata": {
    "namesNumber": 1
  },
  "names": [
    {
      "id": "e0942f50-d1d9-5f5d-b892-38972dff3e2e",
      "name": "Narcissus minor",
      "cardinality": 2,
      "matchType": "Exact",
      "bestResult": {
        "dataSourceId": 1,
        "dataSourceTitleShort": "Catalogue of Life",
        "curation": "Curated",
        "recordId": "45PDW",
        "outlink": "https://www.catalogueoflife.org/data/taxon/45PDW",
        "entryDate": "2021-11-20",
        "sortScore": 9.013153431111759,
        "matchedName": "Narcissus minor L.",
        "matchedCardinality": 2,
        "matchedCanonicalSimple": "Narcissus minor",
        "matchedCanonicalFull": "Narcissus minor",
        "currentRecordId": "45PDW",
        "currentName": "Narcissus minor L.",
        "currentCardinality": 2,
        "currentCanonicalSimple": "Narcissus minor",
        "currentCanonicalFull": "Narcissus minor",
        "isSynonym": false,
        "classificationPath": "Biota|Plantae|Tracheophyta|Liliopsida|Asparagales|Amaryllidaceae|Narcissus|Narcissus minor",
        "classificationRanks": "unranked|kingdom|phylum|class|order|family|genus|species",
        "classificationIds": "5T6MX|P|TP|L2L|SP|694|5XM5|45PDW",
        "editDistance": 0,
        "stemEditDistance": 0,
        "matchType": "Exact",
        "scoreDetails": {
          "infraSpecificRankScore": 0,
          "fuzzyLessScore": 1,
          "curatedDataScore": 1,
          "authorMatchScore": 0.2857143,
          "acceptedNameScore": 1,
          "parsingQualityScore": 1
        }
      },
      "dataSourcesNum": 15,
      "curation": "Curated"
    }
  ]
}
```
So for each requested name we get a `"dataSourcesNum":15`, but just one `bestResult`.
That's fine because it saves a lot of bandwith, but I would add just a bit more information here.
¿Could you include here also a `dataSourceList` of those 15 datasources? (just their ids)

Use case:
When I have only a small list of preferred datasources (i.e. less than 5) and no one of them matches a name, then I would be interested in using API to find out which other datasources include them. But as gnames has 200 datasources, it is much better that I have an ordered list of my secondary preferred lists and match them against the ids returned in `dataSourcesList`. Like this:
1. I have an ordered list of 3 preferred datasources, and a also ordered list of many other secondary datasources
2. None of my 3 preferred datasources matched, so ...
3. I ask gnames again to know `bestResult` and `dataSourcesList`
4. I check which of my secondary datasources is first in `dataSourceList`. If it is current `bestResult`, I just take it. 
5. If not, I explicitly request gnames info from my preferred secondary datasource

**Comment by dimus** [comment]
Oups, sorry @abubelinha , somehow did not notice this issue until now

How about using `all_matches=true`?

`https://verifier.globalnames.org/api/v0/verifications/Isoetes%20longissimum?&all_matches=true`

**Comment by dimus** [comment]
I was thinking about adding data-source ids as well, but was waiting for someone to request it, so I do not create a feature just to create it.

**Comment by abubelinha** [comment]
Thanks for the solution, that works perfect !!
